### PR TITLE
Add MIT open source license

### PR DESCRIPTION
**Pull request by Timendus**
I propose we add a LICENSE file to this repository so the copyright situation is clear.

Questions:
  * Do we agree on GPLv3? I'm not too concerned about this "infecting" other projects, since you don't usually "compile" or "link" with a JSON file. Also, nobody is doing CHIP-8 commercially. But if there are concerns, we could move to LGPL or MIT..?
  * Does this license also apply to for example the descriptions in the database, that have been sourced from other places on the internet? Or do we want to add a notice that says that the license is only applicable to the source and the schemas in this repository..?

### CODE REVIEW

**Comment by tobiasvl** [comment]
I would prefer something like MIT, or perhaps even something more permissive, like CC-0. I'm not a lawyer, but if someone bundles this with their emulator, I don't want a JSON file to impact their licensing.

**Comment by Timendus** [comment]
Yes, that's what LGPL is also for. I don't want to force anyone to use any license. But I do prefer people to have to contribute back to these kinds of projects. LGPL would do just that, MIT or CC0 wouldn't.

Or: we could have a public domain license (or no license at all, since we don't own much of the content anyway) for the JSON, but a more restrictive license (that forces giving back) for the code and the schemas...?

**Comment by Timendus** [comment]
I've swapped the GPL license for an MIT one, with an introduction on which things we don't hold the copyright to. I feel this is a more solid solution now.

**Comment by Timendus** [comment]
If you agree @tobiasvl feel free to merge. Since we're the only two contributers so far, we're also the only ones who need to agree on this, I suppose.

**Comment by tobiasvl** [comment]
Let's do it - there are other potential licenses that could fit this repo better (since it's not code, maybe Creative Commons or something) but MIT is good.

**Pull request merged**
